spring:   
    application:
        name: 'api-gateway'
    config: 
        import: 'optional:configserver:http://localhost:8888'
    cloud:
        config:
            profile: 'dev'
    zipkin:
        base-url: 'http://3.235.22.176:9411'
eureka:
    client:
        serviceUrl:
            defaultZone: 'http://3.235.22.176:8761/eureka'
    
server:
    port: 8765
# eureka:
#     client:
#         serviceUrl:
#             defaultZone: 'http://localhost:8761/eureka'